name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: Android_PROD

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Decode Keystore
      env:
        ENCODED_STRING: ${{ secrets.SIGNING_KEY_STORE_BASE64 }}
        SIGNING_KEY_STORE_PATH: ${{ vars.SIGNING_KEY_STORE_PATH }}
      run:
        echo $ENCODED_STRING | base64 --decode > $SIGNING_KEY_STORE_PATH

    - name: Grant execute permissions for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      env:
        SIGNING_KEY_PASSWORD: ${{ vars.SIGNING_KEY_PASSWORD }}
        SIGNING_KEY_STORE_PATH: ${{ vars.SIGNING_KEY_STORE_PATH }}
        SIGNING_STORE_KEY_ALIAS: ${{ vars.SIGNING_STORE_KEY_ALIAS }}
        SIGNING_STORE_PASSWORD: ${{ vars.SIGNING_STORE_PASSWORD }}
      run: ./gradlew assembleRelease --stacktrace

    - name: Get Release File Name
      id: get-file-name
      run: |
        FILE_NAME=$(find ${{github.workspace}}/app/build/outputs/apk/release/ -name "*.apk" | cut -d "/" -f 7 | cut -d "." -f 4)
        echo "FILE_NAME=$FILE_NAME" >> $GITHUB_OUTPUT

    - name: Upload apk to artifact
      env:
        RELEASE_FILE_NAME: ${{ steps.get-file-name.output.FILE_NAME }}
      uses: actions/upload-artifact@v3
      with:
        name:  ${{ steps.get-file-name.output.FILE_NAME }}
        path: ${{github.workspace}}/app/build/outputs/apk/release/*.apk
