name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment:Android_PROD

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Decode Keystore
      env:
        ENCODED_STRING: ${{ secrets.SIGNING_KEY_STORE_BASE64 }}
        SIGNING_KEY_STORE_PATH: ${{ vars.SIGNING_KEY_STORE_PATH }}
      run:
        echo $ENCODED_STRING | base64 --decode > $SIGNING_KEY_STORE_PATH

    - name: Grant execute permissions for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      env:
        SIGNING_KEY_PASSWORD: ${{ vars.SIGNING_KEY_PASSWORD }}
        SIGNING_KEY_STORE_PATH: ${{ vars.SIGNING_KEY_STORE_PATH }}
        SIGNING_STORE_KEY_ALIAS: ${{ vars.SIGNING_STORE_KEY_ALIAS }}
        SIGNING_STORE_PASSWORD: ${{ vars.SIGNING_STORE_PASSWORD }}
      run: ./gradlew assembleRelease --stacktrace
